### ISSUE TITLE
Error in syslog when "::1" in allowed_hosts parameter

### ISSUE THREAD

**Issue by heaje** [NagiosEnterprises/nrpe#128]
I've installed the EPEL version of NRPE 3.1.0 and immediately run into errors.  I'm not reporting this to EPEL because this appears to be an upstream NRPE issue.  By default, the allowed_hosts parameter looks like this:

```allowed_hosts=127.0.0.1,::1```

Unfortunately, this is causing errors like this in syslog when NRPE starts up:
```nrpe[16986]: add_ipv4_to_acl: Error, ip-address >::1< incorrect length```

Any reason why NRPE would attempt to parse "::1" as an IPv4 address instead of IPv6?  IPv6 is enabled on my server and I can ping "::1" just fine.

I'm running on CentOS 7.1 x86_64.

**Comment by jfrickson** [comment]
I'll get it fixed. Thanks!

**Comment by hedenface** [comment]
Changing the milestone to 3.1.2 to get it out with the next bugfix release.

**Comment by hedenface** [comment]
This was happening because it was just blindly passing all addresses to add_ipv4_to_acl and add_ipv6_to_acl and hoping one succeeded. I added a quick test in add_ipv4 so it can return succesful (e.g. no errors) in the case of an ipv6 address in commit https://github.com/NagiosEnterprises/nrpe/commit/3d596c51b17fa7e6a20a78b30e74a374d36b9380.
