### ISSUE TITLE
Installing NRPE with non root user

### ISSUE THREAD

**Issue by pyzhoN** [NagiosEnterprises/nrpe#156]
Hi, there. I'm working with Ansible, to make a playbook for NRPE. 

When i need to install NRPE with "make install-daemon", i get the following error.

> nagios@testserver:~/src/nrpe-3.2.0$ make install-daemon
> cd ./src/; make install-daemon
> make[1]: Entering directory '/home/nagios/src/nrpe-3.2.0/src'
> /usr/bin/install -c -m 755 -d /home/nagios/local/bin
> /usr/bin/install -c -m 755 ../uninstall /home/nagios/local/bin/nrpe-uninstall
> /usr/bin/install -c -m 755 nrpe /home/nagios/local/bin
> /usr/bin/install -c -m 755 -d /usr/lib/tmpfiles.d
> /usr/bin/install -c -m 644 ../startup/tmpfile.conf /usr/lib/tmpfiles.d/nrpe.conf
> /usr/bin/install: cannot create regular file '/usr/lib/tmpfiles.d/nrpe.conf': Permission denied
> Makefile:63: recipe for target 'install-daemon' failed
> make[1]: *** [install-daemon] Error 1
> make[1]: Leaving directory '/home/nagios/src/nrpe-3.2.0/src'
> Makefile:86: recipe for target 'install-daemon' failed
> make: *** [install-daemon] Error 2

As i'm doing it with other user, that is not root, its fail. I made a simple workaround for this in the makefile file at src directory.

```
nagios@testserver:~/src/nrpe-3.2.0$ cat src/Makefile | grep  "id -u"
	@if test "$(TMPFILESDIR)" != "N/A" -a x$(SRC_TMPFILE) != x -a `id -u` -eq 0 ; then \

```
This is not the "correct" way to do it.. 

Btw, i was configuning it with the proper arguements (using --with-nrpe-user and --with-nrpe-group), but this need to be root to move that file from the src to '/usr/lib/tmpfiles.d/' .. I do not know if this change can make any difference in NRPE operation.

Can be select for being used or not with a correct argument ?

Regards,

**Comment by pyzhoN** [comment]
I found a workaround in the configure step with option --with-init-type=unknown, for skipping this behaviour.

Regads,

**Comment by pyzhoN** [comment]
Sorry for closing this issues.

**Comment by hedenface** [comment]
There is no `--with-tmpfilesd` or anything of the like, if that is what you're asking.

I'm going to close this Issue here - as the method you've implemented locally is probably the best considering the current state of the project.

In a perfect world, the autoconf-macros project would have all of the variables overrideable. If you'd like to open an issue on that project (https://github.com/NagiosEnterprises/autoconf-macros/) then we can implement it there so that it reaches more Nagios projects as they all integrate the updates from there.

Thanks! And good luck!
