### ISSUE TITLE
Fix SSL support for nrpe

### ISSUE THREAD

**Issue by abrist** [NagiosEnterprises/nrpe#4]
See the tracker for potential patch:
http://tracker.nagios.org/view.php?id=90

**Comment by jfrickson** [comment]
I have a complete and backward-compatible update for SSL/TLS in https://github.com/NagiosEnterprises/nrpe/tree/nrpe-2-16-RC2

Please read the README.SSL.md file.

**Comment by jacobamey** [comment]
Hi, question on this fix, do we know when we might possibly see a release update for the epel repository by chance? Currently we are stuck at version 2.15, rolling our own would be difficult due to size of our environment. This update looks like it could potentially fix these CVEs and possibly more. 

CVE-2007-1858
CVE-2013-2566
CVE-2015-2808
CVE-2015-4000
