### ISSUE TITLE
nrpe 3.0.1 does report positive support for all ciphers in cipher_list.

### ISSUE THREAD

**Issue by Houlistonm** [NagiosEnterprises/nrpe#82]
cipher_list in nrpe.cfg = ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD4:!DSS

[openssl cipher list explained](https://www.openssl.org/docs/man1.0.2/apps/ciphers.html)

openssl -V will return a list of all supported ciphers and their hex codes.  I'm going to use the hex codes to save a lot of typing.

testssl.sh tries create a ssl session with nrped using every openssl (1.0.2h) cipher and return a list of ciphers that succeed.

NRPE returned three hex codes (0x9d, 0x3d, 0x35).

I expected the following hex codes (0xc030, 0x3028, 0xc014, 0x9f, 0x6b, 0x39, 0x9d, 0x3d, 0x35, 0xc02f, 0xc027, 0xc013, 0x9e, 0x67, 0x33, 0x9c, 0x3c, 0x2f)

This is the last of the "findings/alerts/reports/issues/etc" with nrpe 3.0.1.  I really appreciate the work you've done and are doing to update the ssl/security for nrpe.

**Comment by Houlistonm** [comment]
Update:  My configuration setting for 
ssl_use_adh = 0
If I change that value to a 1 and restart nrped, I get three more ciphers (0x9f, 0x6b, 0x39).

Looked at the code and I understand why this is happening and I don't have a problem changing my config, but that doesn't account for the balance of the missing ciphers.

**Comment by jfrickson** [comment]
Looking into this

**Comment by hedenface** [comment]
Adding this to 3.1.2 for now for internal documentation reasons, but no promises if it will actually make it in there.

**Comment by hedenface** [comment]
I'd actually almost prefer you to NOT use the Hex codes. Since it is **extremely hard** for me to follow what you're getting at.

By default, the cipher list is `"ALL:!MD5:@STRENGTH"`

When ADH is disabled it is set to your defined cipherlist (or the default) and `":!ADH"` is appended.

When it is set to 1, then your defined cipherlist (or the default) is used.

When it is set to 2, then it is set to `"ADH"` (`ADH@SECLEVEL=0` in latest maint for openssl > 1.1.0)

So, I guess the first thing is ...have you checked that your HEX output matches against the `openssl ciphers -V 'THELIST'` (not `openssl -V 'THELIST'`)?

And are you sure that NRPE is compiled against the version of openssl that your bin points to?

**Comment by hedenface** [comment]
So I looked a bit more into this ...

Everything seems fine to me, remember that along with the `ssl_cipher_list` there is also a `ssl_version` which defaults to `TLSv1+`, which would likely limit the cipher list even further.

I'm going to close it unless you can explicitly display that there is an issue here which I am able to replicate (perhaps upload your `testssl.sh`, etc.)
